// <auto-generated />
namespace BIBSI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _552017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_552017));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051236486_5-5-2017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
